version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development 
    networks:
      - prex_network

  agent:
    build: ./agent
    depends_on:
      - api
    networks:
      - prex_network

networks:
  prex_network:
    driver: bridge
